### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by boshek** [steffilazerte/weathercan#17]
I think that we might consider a different package name for a couple reasons:

- Environment Canada might object to us calling it by their name
- It isn't totally descriptive of what the package does
- It doesn't encompass all the other types of environmental monitoring that ec does.

Some other suggestions:
- canweatheR
- canadaweatheR
- canmeteoR

**Comment by steffilazerte** [comment]
Argh, you're right. I'm not 100% sold on the name options, but I agree that we should probably try to find something better. I don't think I like 'can' because that's not really clearly Canadian (but see below!).

My problem is that I don't like names that are too long, and I don't like capitals (makes things confusing as people always have to remember whether or not there was a capital, and where). I also don't like names that are dull or full of acronyms, so I'm extremely hard to please!

Some brainstorming ideas that I don't completely hate, but none of which I really like (some are yours),

- canadaweather
- canadaweatheR
- canadaweathR
- canadianweather
- climatecanada
- canadaclimate
- canadianRain (although this is a bit silly and not descriptive)

And for some reason I keep coming back to 

- weathercan

I keep thinking how funny it would be to have a logo with a soup can of rain or thunder clouds under a tiny Canadian flag, but that also doesn't really get at what the package is supposed to do.

**Note:** Other packges with weather in R
- weatherr (forcasts)
- weatherData (like ours but mostly American, and no Canadian data)
- rnoaa ( 'NOAA' Weather Data)

I'll keep thinking

**Comment by boshek** [comment]
Well one option is to actually use R to help us figure this out:
```
devtools::install_github("ropenscilabs/available")
available::available("canadaweather")

```
```

> ── canadaweather ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> Name valid: ✔
> Available on CRAN: ✔ 
> Available on Bioconductor: ✔
> Available on GitHub:  ✔ 
> Bad Words: ✔
> Abbreviations: http://www.abbreviations.com/canadaweathe
> Wikipedia: https://en.wikipedia.org/wiki/canadaweathe
> Wiktionary: https://en.wiktionary.org/wiki/canadaweathe
> Urban Dictionary:
>   Not found.
> Sentiment:???

```
Or

```
> available::suggest(title = "R package for downloading weather data from Environment Canada")
[1] "downloading"
> available::suggest(title = "weather data from Environment Canada")
[1] "weather"
```

I like weathercan. And I like the image.

**Comment by steffilazerte** [comment]
Alright, let's do weathercan :)

```
── weathercan ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Name valid: ✔
Available on CRAN: ✔ 
Available on Bioconductor: ✔
Available on GitHub:  ✔ 
Bad Words: ✔
Abbreviations: http://www.abbreviations.com/weathercan
Wikipedia: https://en.wikipedia.org/wiki/weathercan
Wiktionary: https://en.wiktionary.org/wiki/weathercan
Urban Dictionary:
  Not found.
Sentiment:???
```

**Comment by steffilazerte** [comment]
I'll rename it in my branch
