### ISSUE TITLE
dplyr 0.70

### ISSUE THREAD

**Issue by boshek** [steffilazerte/weathercan#23]
I think we should test this with all the changes in dplyr 0.70 especially the tidyeval programming stuff. And I think we should do this ahead of a cran submission. Of course this means learning all that new stuff but it probably has to happen at some point anyway.

**Comment by steffilazerte** [comment]
I agree. The new .data and .env look soooo useful to me, too!

**Comment by boshek** [comment]
For what it is worth, `weathrecan` passes all checks and tests with dplyr 0.70 on Windows 10 machine running R 3.3.3. I'll update R and check back to make sure that is still the case.

**Comment by steffilazerte** [comment]
Oh good, I'll update the DESCRIPTION dplyr version and see how the checks go on travis and appveyor

**Comment by boshek** [comment]
Do you know if travis and appveyor are running with 0.7.0?

**Comment by steffilazerte** [comment]
They should if we specify in the DESCRIPTION that 0.7.0 is required. I'm sure of this, in fact, because the Mac tests on travis.ci are failing (https://travis-ci.org/steffilazerte/weathercan/jobs/243292836) because "Package required and available but unsuitable version: ‘dplyr’" 

This makes me think that dplyr 0.7.0 isn't available on CRAN for macs yet...? No problem with windows (appveyor) or linux (travis.ci)

**Comment by boshek** [comment]
You are correct, good thought. Still on 0.70 for El Capitan at least. In fact, it looks like dplyr 0.7.0 is failing all all sorts of tests/platforms. https://cran.r-project.org/web/checks/check_results_dplyr.html. 

Wait and see?

**Comment by steffilazerte** [comment]
Yes, let's wait and see. It'll give me a chance to rewrite all the filter_(), select_(), etc. functions (as those are being discontinued).
