### ISSUE TITLE
Only import functions we need

### ISSUE THREAD

**Issue by boshek** [steffilazerte/weathercan#26]
From goodpractices::gp(): Do not import packages as a whole, as this can cause name clashes between the imported packages. Instead, import only the specific functions you need.

**Comment by boshek** [comment]
I see that [here](https://github.com/steffilazerte/weathercan/blob/master/R/interpolate.R#L123) you've inserted` @import` rather than [here](https://github.com/steffilazerte/weathercan/blob/master/R/help.R#L65). If there any reason for that? I feel like having all the imports and importfroms might be better in one location? I'm not totally sure what the convention is. Any strong feelings either way?

**Comment by steffilazerte** [comment]
I think my rational was that I import only when really really necessary (and I only used @import lubridate to get at %within%, but if you know how to reference a special function directly, lubridate::`%within%`?? I'd love to do that instead).
So I didn't want to use import lubridate everywhere, only when the function was referenced. No strong feelings either way, except I'd rather not use @import at all.

**Comment by steffilazerte** [comment]
Turns out I didn't truly understand that the `@import` associated with a particular function applied to the whole package (I thought it applied only to the function in question). I've fixed all imports to either be explicit (i.e. lubridate::\`%within%\`(x, y)) or central (i.e. put in the help.R file, as you suggested).
